export const feedbackData = [
  {
    text: 'Great selection, fast delivery, and beautifully packaged books. My go-to store for weekend reads!',
    firstName: 'Jane',
    lastName: 'Doe',
    role: 'Book Lover, Reader',
    avatar: '/img/feedbacks/avatar-jane.jpg',
  },
  {
    text: 'Customer service was super helpful, and my order arrived earlier than expected. Highly recommend!',
    firstName: 'John',
    lastName: ' Smith',
    role: 'Editor, BookMag',
    avatar: '/img/feedbacks/avatar-john.jpg',
  },
  {
    text: 'Love the curated picks and clear descriptions. Makes it easy to find my next favorite book.',
    firstName: 'Emily',
    lastName: 'Johnsonuk',
    role: 'Author, Novelist',
    avatar: '',
  },
  {
    text: 'Amazing experience! I will definitely come back.',
    firstName: 'Liam',
    lastName: 'Green',
    role: 'Book Collector',
    avatar: '',
  },
  {
    text: 'Books came in perfect condition. Thank you!',
    firstName: 'Olivia',
    lastName: 'Brown',
    role: 'Student',
    avatar: '',
  },
  {
    text: 'Fast service and high-quality packaging.',
    firstName: 'Ethan',
    lastName: 'Wilson',
    role: 'Library Assistant',
    avatar: '',
  },
  {
    text: 'Nice recommendations and filters. Easy to use!',
    firstName: 'Ava',
    lastName: 'Davis',
    role: 'Book Blogger',
    avatar: '',
  },
  {
    text: 'Loved the gift wrap option! Perfect for birthdays.',
    firstName: 'Noah',
    lastName: 'Taylor',
    role: 'Dad, Reader',
    avatar: '',
  },
  {
    text: 'User-friendly site and quick checkout.',
    firstName: 'Isabella',
    lastName: 'Moore',
    role: 'Journalist',
    avatar: '',
  },
  {
    text: 'Always on time and reliable.',
    firstName: 'Mason',
    lastName: 'Thomas',
    role: 'Book Reviewer',
    avatar: '',
  },
  {
    text: "One of the best book platforms I've used!",
    firstName: 'Sophia',
    lastName: 'White',
    role: 'Writer',
    avatar: '',
  },
  {
    text: 'Responsive support and great selection!',
    firstName: 'Lucas',
    lastName: 'Hall',
    role: 'Reader',
    avatar: '',
  },
];
